<?php
define('LIMIT', 5);
define('DESTINATION_IMAGE', "\\image\\");
define('SITE_TITLE', "Test");
define('COMPLAINT_SUB_TITLE', "- Complaint Management");
define('FOOD_SUB_TITLE', "- Menu Management");
define('FOODM_SUB_TITLE', "- Food Management");
define('NOTICE_SUB_TITLE', "- Notice Management");
define('NOTICET_SUB_TITLE', "- Notice Management");
define('REPORT_SUB_TITLE', "- Report");
define('ROOM_SUB_TITLE', "- Room Management");
define('ROOMR_SUB_TITLE', "- Room Management");
define('ROOME_SUB_TITLE', "- Room Management");
define('ROOMC_SUB_TITLE', "- Room Management");
define('USER_SUB_TITLE', "- User Management");
define('USERE_SUB_TITLE', "- User Management");
define('USERC_SUB_TITLE', "- User Management");
define('USERU_SUB_TITLE', "- User Management");
define('HOME_SUB_TITLE', "");
define('HOTEL_PG', "PG");
define('NOTICE_DAYS', 30);